Device: cuda
Dataset: cityscapes, Train set: 2975, Val set: 500
[!] Retrain
Traceback (most recent call last):
  File "main.py", line 567, in <module>
    main()
  File "main.py", line 513, in main
    outputs = model(images)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenht/DeepLabv3plus/DeepLabV3Plus-Pytorch/network/utils.py", line 15, in forward
    features = self.backbone(x)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenht/DeepLabv3plus/DeepLabV3Plus-Pytorch/network/utils.py", line 80, in forward
    x = module(x)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenht/DeepLabv3plus/DeepLabV3Plus-Pytorch/network/backbone/resnet.py", line 101, in forward
    out = self.conv1(x)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 72.00 MiB (GPU 0; 23.70 GiB total capacity; 21.70 GiB already allocated; 52.62 MiB free; 21.83 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF