2022-09-09 15:58:30,417 INFO    MainThread:3250936 [wandb_setup.py:_flush():76] Configure stats pid to 3250936
2022-09-09 15:58:30,418 INFO    MainThread:3250936 [wandb_setup.py:_flush():76] Loading settings from /home/chenht/.config/wandb/settings
2022-09-09 15:58:30,418 INFO    MainThread:3250936 [wandb_setup.py:_flush():76] Loading settings from /home/chenht/DeepLabv3plus/DeepLabV3Plus-Pytorch/wandb/settings
2022-09-09 15:58:30,418 INFO    MainThread:3250936 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-09-09 15:58:30,418 INFO    MainThread:3250936 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': 'main.py'}
2022-09-09 15:58:30,418 INFO    MainThread:3250936 [wandb_init.py:_log_setup():461] Logging user logs to /home/chenht/DeepLabv3plus/DeepLabV3Plus-Pytorch/wandb/run-20220909_155830-xhy4oi4k/logs/debug.log
2022-09-09 15:58:30,418 INFO    MainThread:3250936 [wandb_init.py:_log_setup():462] Logging internal logs to /home/chenht/DeepLabv3plus/DeepLabV3Plus-Pytorch/wandb/run-20220909_155830-xhy4oi4k/logs/debug-internal.log
2022-09-09 15:58:30,418 INFO    MainThread:3250936 [wandb_init.py:init():495] calling init triggers
2022-09-09 15:58:30,418 INFO    MainThread:3250936 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {'run_name': 'test_CityScapesV2_2022-09-09_155829', 'wandb': True, 'coder': None, 'data_root': '/home/chenht/datasets/CityScapes', 'dataset': 'cityscapes', 'num_classes': 19, 'model': 'deeplabv3plus_resnet101', 'separable_conv': False, 'output_stride': 16, 'test_only': False, 'save_val_results': 5, 'total_itrs': 30000.0, 'lr': 0.1, 'lr_policy': 'poly', 'step_size': 10000, 'crop_val': False, 'batch_size': 4, 'val_batch_size': 4, 'crop_size': 768, 'ckpt': None, 'continue_training': False, 'loss_type': 'cross_entropy', 'gpu_id': '6', 'weight_decay': 0.0001, 'random_seed': 1, 'print_interval': 10, 'val_interval': 100, 'download': False, 'year': '2012', 'enable_vis': False, 'vis_port': '13570', 'vis_env': 'main', 'vis_num_samples': 8}
2022-09-09 15:58:30,418 INFO    MainThread:3250936 [wandb_init.py:init():548] starting backend
2022-09-09 15:58:30,418 INFO    MainThread:3250936 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-09-09 15:58:30,427 INFO    MainThread:3250936 [backend.py:ensure_launched():217] starting backend process...
2022-09-09 15:58:30,433 INFO    MainThread:3250936 [backend.py:ensure_launched():222] started backend process with pid: 3251018
2022-09-09 15:58:30,434 INFO    MainThread:3250936 [wandb_init.py:init():558] backend started and connected
2022-09-09 15:58:30,437 INFO    MainThread:3250936 [wandb_init.py:init():634] updated telemetry
2022-09-09 15:58:30,453 INFO    MainThread:3250936 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-09-09 15:58:31,469 INFO    MainThread:3250936 [wandb_run.py:_on_init():1919] communicating current version
2022-09-09 15:58:33,235 WARNING MainThread:3250936 [wandb_init.py:init():1064] interrupted
Traceback (most recent call last):
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 698, in init
    run._on_init()
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1920, in _on_init
    self._check_version = self._backend.interface.communicate_check_version(
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 105, in communicate_check_version
    ret = self._communicate_check_version(check_version)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 430, in _communicate_check_version
    result = self._communicate(rec)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
